image: debian:experimental
 
before_script:
  - apt update -qq
  - apt install -y -qq build-essential autoconf autoconf-archive autopoint automake pkg-config libtool m4 autoconf-archive gtk-doc-tools libxml2-utils gobject-introspection libgirepository1.0-dev libglib2.0-dev libjson-glib-dev gettext libcairo2-dev libgtk-4-dev
 
stages:
  - build
 
build-distcheck:
  stage: build
  script:
    - mkdir build
    - cd build
    - ../autogen.sh
    - ../configure
    - make V=1
    - make V=1 distcheck
 
  artifacts:
    paths:
      - build/*
